### ISSUE TITLE
Please create a tag for the latest version

### ISSUE THREAD

**Issue by ncarrier** [ikwzm/dtbocfg#3]
Hello,
I'd like to integrate your driver into a buildroot-based product and the latest version tagged (v0.0.6) doesn't compile due to a change in the API, but the current master's HEAD does work fine.
Having a tag would be cleaner for my integration rather than having to reference a sha1.
Thank you!

**Comment by ikwzm** [comment]
Thank you for the issue.

The latest version is tagged ```v0.0.7```.

**Comment by ncarrier** [comment]
Thank very much!

**Comment by ncarrier** [comment]
Hello,
FWIW, dtbocfg has just been integrated as a buildroot package, thank you
for your work on it!

Le mar. 14 mai 2019 à 11:35, KAWAZOME Ichiro ***@***.***> a
écrit :
